### ISSUE TITLE
Pages where was using http request to API are not SSR

### ISSUE THREAD

**Issue by SzymonPawlak** [m98/universal-cli-starter#1]
brief description: [link](https://medium.com/@szymonpawlak/mohammad-kermani-using-this-solution-i-have-strange-problem-5ece2d447f2b)

For summary, when i use npm run serve: universal, pages without using service with http api request working how i predict, but when i try to use http request pages are not looking as SSR, but works well - i have got asynchronous data even on html

my code:
server.js
```
// GitHub source: server.js
require('zone.js/dist/zone-node');
require('reflect-metadata');
const express = require('express');
var proxy = require('http-proxy-middleware');
const fs = require('fs');
const { platformServer, renderModuleFactory } = require('@angular/platform-server');
const { AppModuleNgFactory, LAZY_MODULE_MAP } = require(`./dist-server/main.bundle`);
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');
const { ngExpressEngine } = require('@nguniversal/express-engine');
// Import the AOT compiled factory for your AppServerModule.
// This import will change with the hash of your built server bundle.
const { AppServerModuleNgFactory } = require(`./dist-server/main.bundle`);
const app = express();
const port = 8000;
const baseUrl = `http://localhost:${port}`;

// proxy middleware options
const proxyMiddlewareOptions = {
    target: <some url>, // target host
    changeOrigin: true,               // needed for virtual hosted sites
    pathRewrite: {
        "^/api" : "",     // rewrite path
    }
};
// Set the engine
app.engine('html', ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [
        provideModuleMap(LAZY_MODULE_MAP)
    ]
}));
// create the proxy (without context)
let proxyApi = proxy(proxyMiddlewareOptions);
app.use('/api', proxyApi);
app.set('view engine', 'html');
app.set('views', './');
app.use('/', express.static('./', { index: false }));
app.get('*', (req, res) => {
    res.render('index', {
        req,
        res
    });
});
app.listen(port, () => {
    console.log(`Listening at ${baseUrl}`);
});

```

Error in terminal :
```
ERROR { Error: Uncaught (in promise): Error
    at resolvePromise (<path>\node_modules\zone.js\dist\zone-node.js:795:31)
    at resolvePromise (<path>\node_modules\zone.js\dist\zone-node.js:766:17)
    at <path>\node_modules\zone.js\dist\zone-node.js:844:17
    at ZoneDelegate.invokeTask (<path>\node_modules\zone.js\dist\zone-node.js:425:31)
    at Object.onInvokeTask (<path>\node_modules\@angular\core\bundles\core.umd.js:3913:33)
    at ZoneDelegate.invokeTask (<path>\node_modules\zone.js\dist\zone-node.js:424:36)
    at Zone.runTask (<path>\node_modules\zone.js\dist\zone-node.js:192:47)
    at drainMicroTaskQueue (<path>\node_modules\zone.js\dist\zone-node.js:602:35)
    at ZoneTask.invokeTask (<path>\node_modules\zone.js\dist\zone-node.js:503:21)
    at ZoneTask.invoke (<path>\node_modules\zone.js\dist\zone-node.js:488:48)
  rejection:
   { [Error]
     __zone_symbol__currentTask:
      ZoneTask {
        _zone: [Object],
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } },
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: { [Error] __zone_symbol__currentTask: [Object] } },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

**Comment by m98** [comment]
The case that the HTTP request is issuing two times (in server side, and browser side) is not hard to fix, I will update this repository as soon as possible.

But about the error in terminal, currently I have no idea. Are you using any third-party library?

**Comment by SzymonPawlak** [comment]
i'm using ngx-translate as a 3th part library and for server proxy http-proxy-middleware to CROSS, but this error only occurs on website with http requests, ngx-translate for testing was deleted. So by that I thought these 2 issue are related, because error only exist when i'm using http request and then page are not SSR.

So i'm waiting :)

**Comment by SzymonPawlak** [comment]
Ok i did one more test, i don't create request in constructor - as before, but on button click, after that page is SSR and i don't have error on console...So now i'm little confused

**Comment by m98** [comment]
Let's talk about the repetitive HTTP requests first.

On the server-side Angular makes all the HTTP requests which are in the constructor, ngOnInit and app start up and you might see the response of the requests on the page. It means all the HTTP requests were issued on the server-side. **Now we have all those required data with a static page and browser (client-side) tries to transfer the app from the server-rendered version to a live version.**

When it comes to **transition**, Angular will run the application on the browser (client-side) again, so obviously, all the construction and methods (and  HTTP requests) will get called again, and subsequently  you will see a flicker in your app which shows some data, and hide them and you will see the live data again. This means there is a problem in transition.

**So what should we do?**
We need a transfer state API from the server to store data on server-side and read/write it from client-side. Angular team are working on this feature _([here](https://github.com/angular/angular/pull/19134))_

For now, to solve this problem temporarily, you can use [Transfer-state](https://github.com/angular/universal-starter/tree/master/custom-webpack/src/modules/transfer-state) (thanks for [@gdi2290](https://github.com/gdi2290)). 

Let me know if you need further information

**Comment by SzymonPawlak** [comment]
Thank you for your help. For summary, if i create some request on constructor in server side rendering i will see on dev tools -> network in html side which i downloaded, data from this request (of course if i render it on html). Such behavior I expected, now i don't see data on html from http request in html file and page is look as normal, no SSR. Sorry for bother you, but is is not clear from me.

**Comment by m98** [comment]
I know what you mean. Your requests are issuing both on the server-side and client-side. right? and there is a flicker.

For now until the [new API](https://github.com/angular/angular/pull/19134) document is not ready, you have to use [transfer-state](https://github.com/angular/universal-starter/tree/master/custom-webpack/src/modules/transfer-state) module and store data from server-side into transfer-state variables, and access them from client-side. When the transition is done, the browser calls all the methods again, but we need to stop it. You will check transfer-state if there is any data for a specific HTTP call right now on transfer-state, if yes, then just return that.

Please let me know if it still does not make sense for you.

**Comment by m98** [comment]
@Sacred90 Could you solve your problem?
